{application,coreelixir,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,ex_doc]},
              {description,"coreelixir"},
              {modules,['Elixir.Coreelixir','Elixir.Introduction',
                        'Elixir.Mymath','Elixir.Mymodules','Elixir.Mynumbes',
                        'Elixir.Myvariable']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
