{application,coreelixir,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,ex_doc]},
              {description,"coreelixir"},
              {modules,['Elixir.Geometry','Elixir.Introduction',
                        'Elixir.MyModules','Elixir.Mymath','Elixir.Mynumbes',
                        'Elixir.Myvariable']},
              {registered,[]},
              {vsn,"0.1.0"}]}.
